CC=gcc
#
#          gprof        
# optimize   |     warnings
# lvl 3 \    |     /    
CFLAGS=-O3 -pg -Wall            
LDFLAGS=-pg 
#        |
#      gprof 
#                                  

SOURCES=pumpd.c ../common/error.c
OBJECTS=$(SOURCES:.c=.o)

EXECUTABLE=pumpd

all: $(SOURCES)
	$(CC) $(CFLAGS) $(LDFLAGS) $(SOURCES) -o $(EXECUTABLE) 

clean:
	rm -f $(OBJECTS) $(EXECUTABLE) gmon.out 
